let nombreComp = [
  { nombre: "Gerzain",
  lastname : "Magaña"},
  { nombre: "Cristian",
  lastname : "Mancilla"},
  { nombre: "Fernando",
  lastname : "Madrigal"},
  { nombre: "Orlando",
  lastname : "Martinez"},
  { nombre: "Rachel",
  lastname : "Perez"},
  { nombre: "Jorge",
  lastname : "Ochoa"},
  { nombre: "Luis Pedro",
  lastname : "Mendoza"},
  { nombre: "Alberto",
  lastname : "Negrete"},
  { nombre: "Róman",
  lastname : "Cebada"},
  { nombre: "Carlos",
  lastname : "Gonzales"},
  { nombre: "Etneciv",
  lastname : "Lopez"},
  { nombre: "Mario",
  lastname : "Ramirez"},
  { nombre: "Mariam",
  lastname : "Rivera"},
  { nombre: "Oscar",
  lastname : "Vera"},
  { nombre: "Jazmin",
  lastname : "Chavez"},
  { nombre: "Javier",
  lastname : "Cipres"},
  { nombre: "Jose Guadalupe",
  lastname : "Deniz Mancilla"}
]
console.log(nombreComp[3].lastname);
